vim.keymap.set("n", "<leader>e", "<CMD>Oil<CR>", { desc = "Open parent directory" })
vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Alternative open parent directory" })
vim.keymap.set("n", "g?", "actions.show_help", { desc = "Show help" })
vim.keymap.set("n", "<CR>", "actions.select", { desc = "Open file/directory" })
vim.keymap.set("n", "<C-s>", "actions.select vertical=true", { desc = "Open in vertical split" })
vim.keymap.set("n", "<C-h>", "actions.select horizontal=true", { desc = "Open in horizontal split" })
vim.keymap.set("n", "<C-t>", "actions.select tab=true", { desc = "Open in new tab" })
vim.keymap.set("n", "<C-p>", "actions.preview", { desc = "Preview file" })
vim.keymap.set("n", "<C-c>", "actions.close", { desc = "Close Oil" })
vim.keymap.set("n", "<C-l>", "actions.refresh", { desc = "Refresh" })
vim.keymap.set("n", "_", "actions.open_cwd", { desc = "Open current working directory" })
vim.keymap.set("n", "gs", "actions.change_sort", { desc = "Change sort" })
vim.keymap.set("n", "gx", "actions.open_external", { desc = "Open with external program" })
vim.keymap.set("n", "g.", "actions.toggle_hidden", { desc = "Toggle hidden files" })

