hl.on("hyprland.start", function () 
  hl.exec_cmd("waybar")
  hl.exec_cmd("hyprctl setcursor XCursor-Pro-Light 28")
  hl.exec_cmd("rm -f \"$HOME/.cache/cliphist/db\"")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
