require("plugins.oil")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.mason")
require("plugins.blink")
require("plugins.lsp")
require("plugins.conform")
require("plugins.neoscroll")
require("plugins.autotag")
require("plugins.luasnip")

